export const Theme = {
  colors: {
    background: '#202225',
    card: '#2B2D31',
    secondaryCard: '#313338',
    accentGold: '#F6C453',
    success: '#57F287',
    danger: '#ED4245',
    info: '#5865F2',
    textPrimary: '#FFFFFF',
    textSecondary: '#C9CDD2',
    textMuted: '#8E9297',
  },
  borderRadius: {
    large: 24,
    medium: 16,
    small: 10,
  },
  fonts: {
    bold: 'bold 24px "Segoe UI", "Segoe UI Emoji", "Segoe UI Symbol", Arial, sans-serif',
    medium: '500 18px "Segoe UI", "Segoe UI Emoji", "Segoe UI Symbol", Arial, sans-serif',
    regular: 'normal 14px "Segoe UI", "Segoe UI Emoji", "Segoe UI Symbol", Arial, sans-serif',
    monospace: '14px Consolas, monospace',
  },
  icons: {
    star: '⭐',
    trophy: '🏆',
    coins: '💰',
    gift: '🎁',
    ticket: '🎟️',
    music: '🎵',
    game: '🎮',
    stats: '📊',
    chartUp: '📈',
    chartDown: '📉',
    shield: '🛡️',
    user: '👤',
    chat: '💬',
    volume: '🔊',
    folder: '📁',
    settings: '⚙️',
    block: '🚫',
    check: '✅',
    cross: '❌',
    party: '🎉',
  }
};
